name       : kdev-php
version    : 5.5.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.5.2/src/kdev-php-5.5.2.tar.xz : 05b8a2f1bdc86ce03f4c5121c29dadcf32daf52b34bbf54fbcd250494f3bd6a2
license    : GPL-2.0-or-later
component  : programming.tools
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Core)
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
