name       : kdev-php
version    : 5.4.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.4.0/src/kdev-php-5.4.0.tar.xz : f77fc0918732fdd8ff6969a8fbb857bdd36de759d0f371cbb5e9803bde4ce675
license    : GPL-2.0-or-later
component  : programming.tools
libsplit   : no
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
