name       : kdev-php
version    : 22.04.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kdev-php-22.04.3.tar.xz : 1a267c2eaed3658ac0b2dacc28956867eab7608bacf57b3041952a868f27c915
license    : GPL-2.0-or-later
component  : programming.tools
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Core)
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
