name       : kdev-php
version    : 5.5.2
release    : 13
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.5.2/src/kdev-php-5.5.2.tar.xz : 05b8a2f1bdc86ce03f4c5121c29dadcf32daf52b34bbf54fbcd250494f3bd6a2
license    : GPL-2.0-or-later
component  : programming.tools
libsplit   : no
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
