name       : kdev-php
version    : 5.4.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.4.4/src/kdev-php-5.4.4.tar.xz : 6047265553018f30c6f55ecfa3b095d8bf5c629223b078e0968c75710f1f670e
license    : GPL-2.0-or-later
component  : programming.tools
libsplit   : no
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
