name       : kdev-php
version    : 5.2.4
release    : 3
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.2.4/src/kdev-php-5.2.4.tar.xz : 47891ab1b8dfc0a686ff37435e7781eebf2236bf8b52d85987cfbba618bf454a
license    : GPL-2.0
component  : programming.tools
libsplit   : no
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
