name       : kdev-php
version    : 5.3.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.3.1/src/kdev-php-5.3.1.tar.xz : 3f4d22e9109832c5d9f227e4d6ddee013543fa6a4814016f2ab18080673812d5
license    : GPL-2.0
component  : programming.tools
libsplit   : no
summary    : PHP support for KDevelop
description: |
    KDevelop plugin which provides PHP language support.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
